title: LCC Fusion Project
baseurl: "/LccFusionProject"
description: LCC Fusion Project is a DIY project providing hardware and software for Model Train Layout Automation using NMRA Layout Command Control (LCC)
url: https://patfleming.github.io
repository: https://github.com/patfleming/LccFusionProject
permalink: /:title/:path/
theme: just-the-docs
remote_theme: "just-the-docs/just-the-docs"
logo: /assets/images/LCCFusionLogo.png
# favicon_ico: "/assets/images/favicon.ico"
aux_links:
  "LCC Fusion Documentation": https://patfleming.github.io/LccFusionProject/
  "LCC Fusion GitHub Repository": https://github.com/patfleming/LccFusionProject
  "Sitemap": "/LccFusionProject/sitemap/"
aux_links_new_tab: true

exclude:
  - assets/downloads/LccFusion-ESP32-3.0.5.zip
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

mermaid:
  version: "11.3.0"
  initialize: true

search_enabled: true
button: true

plugins:
  - jekyll-default-layout
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-remote-theme

# Custom variables
docPath: resources
docTopics: resources/Topics

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true  # Disables any interfering syntax highlighting

# default tags based on location of the .md file
defaults:
  - scope:
      path: "_builder/Cards" # tags for this directory
    values:
      tags: ["PCB Build", "Hardware", "Cards"]
  - scope:
      path: "_builder/Breakout_Boards" # tags for this directory
    values:
      tags: ["PCB Build", "Hardware", "Breakout Boards"]
  - scope:
      path: "_builder/Tips" # tags for this directory
    values:
      tags: ["Builder Tips"]
  - scope:
      path: "_planning"
    values:
      tags: ["Planning for LCC", "Layout Architect"]
  - scope:
      path: "_quickstart"
    values:
      tags: ["Quick Start Guides"]
  - scope:
      path: "_setup"
    values:
      tags: ["Layout Deployment"]


#variables
gerber_dir: /builder/GerberFiles/  # don't use leading '/' since this need to reference a file from the root. don't use trailing slash after the .zip name since we're working with a file.

# Reading Files

collections:
  planning:
    output: true
    permalink: "/planning/:path/"
  builder:
    output: true
    permalink: "/builder/:path/"
  setup:
    output: true
    permalink: "/setup/:path/"
  quickstart:
    output: true
    permalink: "/quickstart/:path/"

color_scheme: dark
nav_scheme: wider
nav_enabled: true

# External navigation links
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

just_the_docs:
  custom_css: "assets/css/custom.css"
  nav_footer_link: true # Set this to false to disable the footer link
  collections:
    builder:
      name: Builder's Bench
      nav_fold: true
    setup:
      name: Setup & Configuration
      nav_fold: true
    quickstart:
      name: Quickstart Guides
      nav_fold: true
    planning:
      name: Planning For LCC
      nav_fold: true
